### ISSUE TITLE
Environment `mppt_shaded` doesn't exist

### ISSUE THREAD

**Issue by peiseng** [marianodepaula/mppt_ddpg#1]
Hi, 

Can you show the method of accessing to 'mmpt_shaded' environment? 

https://github.com/loavila/mppt-gym does not provide 'mmpt_shaded' environment. 

Thanks.

**Comment by IgnacioCarlucho** [comment]
Hi @PeiSeng,

Thanks for your comment! 

The mppt_shaded environment is not on the main branch, you will find it in the branch [rama2_mdp](https://github.com/loavila/mppt-gym/tree/rama2_mdp).

You can then use it with:

```
    import gym
    import gym_mppt
    env = gym.make('mppt_shaded-v0')
```

We will try to improve the readme and point to this branch later this week. 

Please let us know if there is anything else you need help with!

**Comment by peiseng** [comment]
Thanks for the fast response. I will close this issue.
