### ISSUE TITLE
Inquiry on number of episode and maximum number of samples per episode

### ISSUE THREAD

**Issue by peiseng** [marianodepaula/mppt_ddpg#2]
Hi, 

In your paper, the number of episode is set to be 30k and the maximum number of samples per episode is set to be 100. However, in this repo, the number of epoch/episode is set to be 15k and maximum number of steps per epoch is set 45. May I know which is the correct setting? 

Thanks.

**Comment by IgnacioCarlucho** [comment]
Hi @PeiSeng, 

The correct is as said in the paper, 30k and 100 steps per episode. 

Let me know if there's anything else you need help with!
